DROP TABLE IF EXISTS exhibits;
DROP TABLE IF EXISTS artists;

CREATE TABLE artists (
  id SERIAL8 PRIMARY KEY,
  name VARCHAR(255)
);

CREATE TABLE exhibits (
  id SERIAL8 PRIMARY KEY,
  artist_id INT4 REFERENCES artists(id) ON DELETE CASCADE,
  category VARCHAR(255)
);
