DROP TABLE IF EXISTS artists;
DROP TABLE IF EXISTS exhibits;

CREATE TABLE artists (
  id INT4 PRIMARY KEY,
  name VARCHAR(255)
);

CREATE TABLE exhibits (
  id INT4 PRIMARY KEY,
  artist_id INT4 REFERENCES artists(id) ON DELETE CASCADE,
  category VARCHAR(255)
);
